name: Laravel

# events that trigger the workflow,when push and pull request is done in main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# Code that will execute
jobs:
  laravel-tests:

    runs-on: ubuntu-latest
  # Step includes in a jobs
    steps:
    # Setup the php enviroment with specific version
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
        # Checkout The code from repository
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      # Install Project Dependencies
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Setup Node.js
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install npm dependencies
      run: npm install

    - name: Generate key
      run: php artisan key:generate
      # Set Directory permission for the storage
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
#     - name: Create Database
#       run: |
#         mkdir -p database
#         touch database/database.sqlite
# Run Test
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE:  ":memory:"
      run: vendor/bin/phpunit

